services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: hotelchain
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hotelchain_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hoteleria-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - hoteleria-network

  backend:
    build:
      context: ./backend-hoteleria
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://hotelchain:password123@postgres:5432/hotelchain_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend-hoteleria:/app
      - /app/node_modules
    networks:
      - hoteleria-network

  frontend:
    build:
      context: ./frontend-hoteleria
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
      - PORT=3001
    depends_on:
      - backend
    volumes:
      - ./frontend-hoteleria:/app
      - /app/node_modules
    networks:
      - hoteleria-network

volumes:
  postgres_data:

networks:
  hoteleria-network:
    driver: bridge
